# Generated by Django 2.2.4 on 2019-08-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='server_mem',
            field=models.CharField(default='', max_length=32, verbose_name='内存总大小'),
        ),
    ]
