# Generated by Django 2.2.4 on 2019-08-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bussiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_chooics', models.IntegerField(choices=[(1, 'O2M300'), (2, 'O2M500'), (3, 'O2M800'), (4, 'IM800')])),
                ('virIP', models.GenericIPAddressField(db_index=True, verbose_name='业务IP')),
                ('application', models.CharField(db_index=True, max_length=200, verbose_name='业务名称')),
                ('port', models.IntegerField(max_length=32, null=True, verbose_name='应用端口')),
                ('component', models.CharField(max_length=100, verbose_name='组件用途')),
                ('principal', models.CharField(max_length=32, verbose_name='开发负责人')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('note', models.CharField(max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'bussiness',
            },
        ),
    ]
