# Generated by Django 2.2.4 on 2019-08-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bussiness',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='business_chooics',
            field=models.IntegerField(choices=[(0, '---请选择---'), (1, 'O2M300'), (2, 'O2M500'), (3, 'O2M800'), (4, 'IM800'), (5, '供应链')]),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='port',
            field=models.IntegerField(default='', null=True, verbose_name='应用端口'),
        ),
        migrations.AlterModelTable(
            name='bussiness',
            table=('bussiness',),
        ),
    ]
