# Generated by Django 2.2.4 on 2019-08-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20190808_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bussiness',
            options={},
        ),
        migrations.AlterModelTable(
            name='bussiness',
            table='bussiness',
        ),
    ]
